def frequency_table(genome, k):
    freq_map = {}
    for i in range(len(genome) - k +1):
        if genome[i:i+k] not in freq_map:
            freq_map[genome[i:i+k]] = 1
        else:
            freq_map[genome[i:i + k]] +=1
    return freq_map


def find_clumps(genome, k, L, t):
    patterns = []
    for i in range(len(genome) -L +1):
        freqmap = frequency_table(genome[i:i+L], k)
        for key, value in freqmap.items():
            if freqmap[key] >= t:
                patterns.append(key)
    unique_patterns = list(set(patterns))
    result_string = " ".join(unique_patterns)
    return result_string

genome = "TCGCTGAGACTACTGTGCCCGAGAGGCGACACTCGCTCATAAGTTCCTGCAAGTGGATTGTCCGCAGAGTCGCTAAACGGGTGGCAGGACTGCGCCATGGGAGCCAGGTATTGTTTGTGTGGCCTATACCGGCAAAGGCTTCCTAAAGGCTTCCTCTTCCTCTGCAACTTGGCTATCCTGTAGGTGTGTCCGGCTAGATAGTGATACGACCACGGACCGCAGAAGTAGTGCATGGGAAAGCATTGGTTATCCGCCCTAAGAGGTCAAATACTGCCCTTTCAGTCCGCCATGTACGCACAGGCCGTATGCCTCGGCTTGTGGAGGTTCAGGCCACATGCGCCTATTCAATGTGTCTATTCAATGGGCATTGAAGTGACCCTTGGTAGCGATTTAACAGACCAACAAGAGATGATGAGAATTGTCTCTCGTAAATTGTAGGAGAGCGGTCATAACGGGAAGCCCATGAATAACAATAAACAGCGAATATAGCAGGACTATCTGACAAGACGGAGCGCTGCTCCAGGTCGAGACTCACAACTCGATTGGAGAGTGGCTGTGCGATCAAGGACATCAGGGTCGGAATTGCAACGTTTCCGCACACCACTCCTCTATCACTCCTCTATCTAAGGCGAAATCCCCCTGCGACCCCCTGCGACCCTGCGACCCTAATAATCATAATAATCCCCACCCACTCGGACAATCGGCCTCGGACAAATTTCGTGTAATATCGGCGATTTTTGGATAGGGATCGTAGTCGATCGTTACGGGTGTCCGTCAATTATCTGCCGTGATAGGGTATATCTTGAGTAGGTGAACACTGGGTTCTACGAATTACCGTCCCACAATGATCCCCAAGTCGTCGGACTGCTATATCGCGAAACTACGTATCGTATACTACGTATCCAGGGCCGCTCGAATGATTGAGTGCCGCACATACTTACATCCCCATGGCTAGCGCGACGATGCGTTGTTCATAACGACCGTATGCCACTCCTGGGCGTTGTACGTTTAGTATACTCCAAGTTTCTACTATGCTCCGCTGAGACTGATAACCCAGAGGCCGTCTGGTTGTACAATTTAATACCAAGGCATGGCTATCTTATACTCGTGTAGACCGCAGTTCTTCCATAATGCAAGACGGGGCCTGTTAGAGTATTACCTGCTAGGGGCTAGGTTTAGGCTAGGTTTATATACAACTATGCACCATGTGTAAGAAGGCAGCCACAACAGGTGGACATGCTAATATCAGCGACGATGGCATCGCAAAGGACCAATGCTGCCTGGGTTACTGGGTATTGACATCAGCCCTGACCTGATAACCTGATCCTGATAACTAGGAACTCTAAAGTTTACGAATTTCATAAAAAATAGGCAGGAGAAATAGGCAGAGGCTGTTGGGTGATTTAGGTTCGCTTTCTCTGGAGCCGCCTGATTTTCGGATTAAAGTGTAGACTTCCTACTCAACTATTTCCCAACCTTAAAAAATGTGGCTACACGTCTCGATGCGCTCTAAGATCCGGAGATCCGGATCCTCCGGAGAGCGCTGTACGTCTGTCGAGATTTTACATCAAGAATGTTTAGTTCGCTTAGATCTAGCTGCCCCGACCCGATCCCAGATGGATACAACTGCCGGTTGGTGGTTATTAGTCCAGCCGAGCATTGGTGGACGAGCATTGGGGACGAGTTATCTATCGTACGAGTTATCGCTAGAACCGGTCCTCTACAGGTCATATGGCCAAGTATCGACCATATCTGCCATGGTGACCACGTACCGTGCCATTCGAAAGCTCTCGGAGGAATAGCTA"
k = 10
L = 26
t = 3
print(find_clumps(genome, k, L, t))



